# Generated by Django 4.1.4 on 2022-12-26 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('WeekDays', models.CharField(max_length=300)),
                ('Is_Closed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CountryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_Name', models.CharField(max_length=30)),
                ('country_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.countrymaster')),
            ],
        ),
        migrations.CreateModel(
            name='Training_Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nsdc_Registration_Number', models.CharField(max_length=30)),
                ('Training_Partner_Name', models.CharField(max_length=30)),
                ('Legal_Entity_Name', models.CharField(max_length=30)),
                ('Contact_Person_Name', models.CharField(max_length=30)),
                ('Contact_Person_Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=30)),
                ('Contact_Person_Phone', models.CharField(max_length=30)),
                ('Alternate_Email', models.EmailField(max_length=254, null=True)),
                ('Address', models.TextField()),
                ('IsActive', models.IntegerField()),
                ('IsDeleted', models.BooleanField()),
                ('CreatedBy', models.CharField(max_length=30)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBy', models.CharField(max_length=30)),
                ('ModifiedDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Training_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerno', models.CharField(max_length=50)),
                ('Training_Center_Name', models.CharField(max_length=30)),
                ('Address1', models.TextField()),
                ('Address2', models.TextField()),
                ('Pin_Code', models.IntegerField()),
                ('Contact_Name', models.CharField(max_length=30)),
                ('Contact_Email', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=15)),
                ('Contact_No', models.CharField(max_length=15)),
                ('IsDeleted', models.IntegerField()),
                ('IsActive', models.IntegerField()),
                ('CreatedBy', models.CharField(max_length=30)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBy', models.CharField(max_length=30)),
                ('ModifiedDate', models.DateField()),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.citymaster')),
                ('Training_Partner_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.training_partner')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.statemaster')),
            ],
        ),
        migrations.CreateModel(
            name='CourceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=30)),
                ('Duration', models.CharField(max_length=30)),
                ('Training_Center_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.training_center')),
            ],
        ),
        migrations.AddField(
            model_name='citymaster',
            name='State_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.statemaster'),
        ),
        migrations.CreateModel(
            name='CandidateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Candidate_Email', models.EmailField(max_length=254)),
                ('Candidate_password', models.CharField(max_length=15)),
                ('Phone_no', models.CharField(max_length=15)),
                ('DOB', models.DateField(default=False, null=True)),
                ('Address1', models.TextField(null=True)),
                ('Address2', models.TextField(null=True)),
                ('pincode', models.CharField(max_length=8, null=True)),
                ('Gender', models.CharField(max_length=10, null=True)),
                ('adhar_Number', models.IntegerField()),
                ('willing_to_relocate', models.CharField(max_length=50, null=True)),
                ('differently_abled', models.CharField(max_length=30)),
                ('Job_role', models.CharField(max_length=30, null=True)),
                ('Training_Type', models.CharField(max_length=30, null=True)),
                ('Training_Status', models.CharField(max_length=30, null=True)),
                ('Placed_Status', models.CharField(max_length=30, null=True)),
                ('Qualification', models.CharField(max_length=50, null=True)),
                ('Training_Scheme_Name', models.CharField(max_length=30)),
                ('IsDeleted', models.IntegerField()),
                ('IsActive', models.BooleanField()),
                ('CreatedBy', models.CharField(max_length=30)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBy', models.CharField(max_length=30)),
                ('ModifiedDate', models.DateField()),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('otp_is_used', models.BooleanField(blank=True, null=True)),
                ('City_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.citymaster')),
                ('Course_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.courcemaster')),
                ('State_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.statemaster')),
                ('Training_Center_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.training_center')),
                ('Training_Partner_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.training_partner')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.batchmaster')),
                ('Candidate_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.candidatemaster')),
                ('Center_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.courcemaster')),
            ],
        ),
        migrations.CreateModel(
            name='bulk_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_upload_file', models.FileField(upload_to='')),
                ('TotalRecord', models.IntegerField()),
                ('TotalSkip', models.IntegerField()),
                ('TotalSuccess', models.IntegerField()),
                ('UploadedBy', models.CharField(max_length=30)),
                ('UploadedDate', models.DateField()),
                ('Training_Center_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.training_center')),
                ('Training_Partner_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.training_partner')),
            ],
        ),
        migrations.AddField(
            model_name='batchmaster',
            name='Course_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.courcemaster'),
        ),
        migrations.AddField(
            model_name='batchmaster',
            name='Training_Center_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.training_center'),
        ),
    ]
