# Generated by Django 4.1.4 on 2022-12-26 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TrainingPartner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry_partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerno', models.CharField(max_length=50)),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Partner_Type', models.CharField(max_length=30)),
                ('Legal_Entity_Name', models.CharField(max_length=30)),
                ('SPOC_Name', models.CharField(max_length=30)),
                ('SPOC_Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=30)),
                ('SPOC_Phone', models.CharField(max_length=15)),
                ('Full_Address', models.TextField()),
                ('PIN_Code', models.CharField(max_length=8)),
                ('Office_Phone_No', models.CharField(max_length=15)),
                ('Website_Link', models.CharField(max_length=30)),
                ('IsActive', models.IntegerField()),
                ('IsDeleted', models.IntegerField()),
                ('CreatedBy', models.CharField(max_length=30)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBy', models.CharField(max_length=30)),
                ('ModifiedDate', models.DateField()),
                ('District_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.citymaster')),
                ('State_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.statemaster')),
            ],
        ),
        migrations.CreateModel(
            name='Partner_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RPL_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trining_type', models.CharField(max_length=50)),
                ('Target', models.IntegerField()),
                ('Job_role', models.CharField(max_length=30)),
                ('Area', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('SPOC_Name', models.CharField(max_length=30)),
                ('SPOC_Number', models.CharField(max_length=12)),
                ('SPOC_Email', models.EmailField(max_length=254)),
                ('SPOC_Designation', models.CharField(max_length=30)),
                ('Is_deleted', models.BooleanField()),
                ('IsActive', models.BooleanField()),
                ('City_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.citymaster')),
                ('Country_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.countrymaster')),
                ('Industry_partner_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IndustryPartner.industry_partner')),
                ('State_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.statemaster')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Name', models.CharField(max_length=50)),
                ('Job_type', models.CharField(max_length=50)),
                ('Job_salary', models.IntegerField()),
                ('Job_Description', models.TextField()),
                ('Requirements', models.CharField(max_length=50)),
                ('Number_Of_Requirements', models.IntegerField()),
                ('Job_Add_Date', models.DateField(blank=True, null=True)),
                ('Job_Ending_Date', models.DateField(blank=True, null=True)),
                ('Experience', models.IntegerField()),
                ('Qualification', models.CharField(max_length=200)),
                ('IsActive', models.IntegerField()),
                ('IsDeleted', models.IntegerField()),
                ('createby', models.CharField(max_length=30)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBy', models.CharField(max_length=30)),
                ('ModifiedDate', models.DateField()),
                ('City_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.citymaster')),
                ('Country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.countrymaster')),
                ('Industry_partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IndustryPartner.industry_partner')),
                ('State_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.statemaster')),
            ],
        ),
        migrations.CreateModel(
            name='Hiring_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsActive', models.IntegerField()),
                ('IsDeleted', models.IntegerField()),
                ('createby', models.CharField(max_length=30)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBy', models.CharField(max_length=30)),
                ('ModifiedDate', models.DateField()),
                ('Job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IndustryPartner.job_posting')),
                ('Training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.training_partner')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.candidatemaster')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_job_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_status', models.CharField(max_length=30)),
                ('Candidate_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.candidatemaster')),
                ('Job_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IndustryPartner.job_posting')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_apply_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedBy', models.CharField(max_length=30)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBy', models.CharField(max_length=30)),
                ('ModifiedDate', models.DateField()),
                ('Candidate_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.candidatemaster')),
                ('Trainingpartner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPartner.training_partner')),
            ],
        ),
    ]
